In [1]:
import pandas as pd
import numpy as np

#WORKING ON THE DATASETS CONTAINING DATA RELATED TO SURVEY AND TEST RESULTS
#There are three txt files

In [2]:
#Loading datasetes in Pandas Dataframes

survey1= pd.read_csv('TALQdata1.txt', sep="¢", header=None)
print(survey1.shape)
survey2= pd.read_csv('TALQdata2.txt', sep="¢", header=None)
print(survey2.shape)
survey3= pd.read_csv('TALQdata3.txt', sep="¢", header=None)
print(survey3.shape)

/Users/cesurdagli/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: ParserWarning: Falling back to the 'python' engine because the separator encoded in utf-8 is > 1 char long, and the 'c' engine does not support such separators; you can avoid this warning by specifying engine='python'.
  This is separate from the ipykernel package so we can avoid doing imports until

(521078, 74)

/Users/cesurdagli/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: ParserWarning: Falling back to the 'python' engine because the separator encoded in utf-8 is > 1 char long, and the 'c' engine does not support such separators; you can avoid this warning by specifying engine='python'.
  """

(1109826, 74)

/Users/cesurdagli/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: ParserWarning: Falling back to the 'python' engine because the separator encoded in utf-8 is > 1 char long, and the 'c' engine does not support such separators; you can avoid this warning by specifying engine='python'.
  import sys

(571377, 74)

In [47]:
# Combining three datasets using pandas concat function
merged_survey = pd.concat([survey1, survey2, survey3])
print(merged_survey.shape)

(2202281, 74)

In [48]:
merged_survey= merged_survey.reset_index(drop=True)

In [49]:
#Droping duplicated features since the survey questions were saved twice.
merged_survey=merged_survey.drop(merged_survey.columns[9:39], axis=1)

In [50]:
merged_survey.shape

(2202281, 44)

In [51]:
#naming the columns

merged_survey.columns=['email' , 'name', 'pass_fail', 'right_question', 'wrong_question', 'testID', 'testTakenTime', 'testDuration', 'testLevel', 'taskCompleted', 'viewedVideoCases', 'viewedDemVideos', 'integrationCompleted', 'practiceTestTaken', 'quality_Satisfaction1', 'ALT1NBR', 'authenticProblems1', 'demonstration1', 'application1', 'activation1', 'ALT2', 'ALT3', 'quality_Satisfaction2', 'demonstration2', 'demonstration3', 'ALT4', 'authenticProblems2', 'integration1', 'activation2', 'authenticProblems3', 'integration2', 'demonstration4NBR', 'application3', 'quality_Satisfaction3NBR', 'integration3', 'activation3', 'application4', 'demonstration5', 'quality_Satisfaction4NBR', 'certificationDate', 'certificationTestEarnedDate', 'IP', 'comments', 'email1']

In [8]:
a=['quality_Satisfaction1', 'ALT1NBR',
       'authenticProblems1', 'demonstration1', 'application1', 'activation1',
       'ALT2', 'ALT3', 'quality_Satisfaction2', 'demonstration2',
       'demonstration3', 'ALT4', 'authenticProblems2', 'integration1',
       'activation2', 'authenticProblems3', 'integration2',
       'demonstration4NBR', 'application3', 'quality_Satisfaction3NBR',
       'integration3', 'activation3', 'application4', 'demonstration5',
       'quality_Satisfaction4NBR'] 
for col in a:
    print(col, ':', len(merged_survey[col].unique()))
    print(merged_survey[col].unique())
    merged_survey[col] = merged_survey[col].map({1:1, 2:2, 3:3, 4:4, 5:5})
    print(merged_survey[col].unique())

quality_Satisfaction1 : 7
[nan  4.  5.  3.  0.  1.  2.]
[nan  4.  5.  3.  1.  2.]
ALT1NBR : 7
[nan  2.  1.  0.  3.  4.  5.]
[nan  2.  1.  3.  4.  5.]
authenticProblems1 : 7
[nan  5.  3.  0.  4.  2.  1.]
[nan  5.  3.  4.  2.  1.]
demonstration1 : 7
[nan  5.  3.  4.  0.  2.  1.]
[nan  5.  3.  4.  2.  1.]
application1 : 7
[nan  5.  4.  0.  1.  3.  2.]
[nan  5.  4.  1.  3.  2.]
activation1 : 7
[nan  5.  4.  3.  0.  2.  1.]
[nan  5.  4.  3.  2.  1.]
ALT2 : 7
[nan  4.  2.  3.  0.  5.  1.]
[nan  4.  2.  3.  5.  1.]
ALT3 : 7
[nan  5.  4.  2.  0.  3.  1.]
[nan  5.  4.  2.  3.  1.]
quality_Satisfaction2 : 7
[nan  4.  5.  0.  2.  3.  1.]
[nan  4.  5.  2.  3.  1.]
demonstration2 : 7
[nan  5.  4.  0.  1.  3.  2.]
[nan  5.  4.  1.  3.  2.]
demonstration3 : 7
[nan  5.  4.  3.  0.  2.  1.]
[nan  5.  4.  3.  2.  1.]
ALT4 : 7
[nan  5.  4.  2.  0.  3.  1.]
[nan  5.  4.  2.  3.  1.]
authenticProblems2 : 7
[nan  5.  4.  2.  0.  3.  1.]
[nan  5.  4.  2.  3.  1.]
integration1 : 7
[nan  5.  4.  3.  0.  2.  1.]
[nan  5.  4.  3.  2.  1.]
activation2 : 7
[nan  5.  4.  2.  0.  3.  1.]
[nan  5.  4.  2.  3.  1.]
authenticProblems3 : 7
[nan  5.  4.  3.  0.  2.  1.]
[nan  5.  4.  3.  2.  1.]
integration2 : 7
[nan  5.  4.  3.  0.  2.  1.]
[nan  5.  4.  3.  2.  1.]
demonstration4NBR : 15
[nan 1.0 2.0 0.0 4.0 3.0 5.0 '1' '2' '0' '3' '4' '5' None '/']
[nan  1.  2.  4.  3.  5.]
application3 : 15
[nan 5.0 4.0 0.0 2.0 3.0 1.0 '4' '5' '0' '3' '1' '2' None '/']
[nan  5.  4.  2.  3.  1.]
quality_Satisfaction3NBR : 15
[nan 2.0 0.0 3.0 1.0 4.0 5.0 '1' '3' '2' '4' '0' '5' None '/']
[nan  2.  3.  1.  4.  5.]
integration3 : 15
[nan 5.0 4.0 0.0 2.0 3.0 1.0 '4' '3' '2' '5' '0' '1' None '/']
[nan  5.  4.  2.  3.  1.]
activation3 : 15
[nan 5.0 4.0 3.0 0.0 2.0 1.0 '3' '4' '2' '5' '0' '1' None
 'e07426nb@163.com']
[nan  5.  4.  3.  2.  1.]
application4 : 7
[nan  5.  4.  3.  0.  2.  1.]
[nan  5.  4.  3.  2.  1.]
demonstration5 : 7
[nan  5.  4.  0.  2.  3.  1.]
[nan  5.  4.  2.  3.  1.]
quality_Satisfaction4NBR : 15
[nan 2.0 1.0 0.0 3.0 4.0 5.0 '2' '1' '3' '4' '5' '0' None '/']
[nan  2.  1.  3.  4.  5.]

In [10]:
#This dataset contains negatively worded questions so I need to reverse those columns for negatively worded survey items.

merged_survey['ALT1Reversed'] = merged_survey['ALT1NBR'].map({1:5, 2:4, 3:3, 4:2, 5:1})
merged_survey['demonstration4Reversed'] = merged_survey['demonstration4NBR'].map({1:5, 2:4, 3:3, 4:2, 5:1})
merged_survey['quality_Satisfaction3Reversed'] = merged_survey['quality_Satisfaction3NBR'].map({1:5, 2:4, 3:3, 4:2, 5:1})
merged_survey['quality_Satisfaction4Reversed'] = merged_survey['quality_Satisfaction4NBR'].map({1:5, 2:4, 4:2, 3:3, 5:1})
merged_survey[['ALT1Reversed', 'ALT1NBR', 'demonstration4Reversed', 'demonstration4NBR', 'quality_Satisfaction3Reversed','quality_Satisfaction3NBR', 'quality_Satisfaction4Reversed', 'quality_Satisfaction4NBR' ]].head(100)

,ALT1Reversed,ALT1NBR,demonstration4Reversed,demonstration4NBR,quality_Satisfaction3Reversed,quality_Satisfaction3NBR,quality_Satisfaction4Reversed,quality_Satisfaction4NBR
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4.0,2.0,5.0,1.0,4.0,2.0,4.0,2.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,4.0,2.0,4.0,2.0,4.0,2.0,5.0,1.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,5.0,1.0,2.0,4.0,3.0,3.0,3.0,3.0
98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Droping rows rated the very similar items as strongly aggree and strongly disagree to have more realible data only 

merged_survey = merged_survey.drop(merged_survey[((merged_survey.quality_Satisfaction1 == 5)|(merged_survey.quality_Satisfaction1 == 4)) & ((merged_survey.quality_Satisfaction4Reversed== 1) | (merged_survey.quality_Satisfaction4Reversed== 2))].index)
merged_survey = merged_survey.drop(merged_survey[((merged_survey.quality_Satisfaction1 == 1)|(merged_survey.quality_Satisfaction1 == 2)) & ((merged_survey.quality_Satisfaction4Reversed== 5) | (merged_survey.quality_Satisfaction4Reversed== 4))].index)

print(merged_survey.shape)

merged_survey = merged_survey.drop(merged_survey[((merged_survey.demonstration1 == 5)|(merged_survey.demonstration1 == 4)) & ((merged_survey.demonstration4Reversed== 1) | (merged_survey.demonstration4Reversed== 2))].index)
merged_survey = merged_survey.drop(merged_survey[((merged_survey.demonstration1 == 1)|(merged_survey.demonstration1 == 2)) & ((merged_survey.demonstration4Reversed== 5) | (merged_survey.demonstration4Reversed== 4))].index)

print(merged_survey.shape)

merged_survey = merged_survey.drop(merged_survey[((merged_survey.ALT2 == 5)|(merged_survey.ALT2 == 4)) & ((merged_survey.ALT1Reversed== 1) | (merged_survey.ALT1Reversed== 2))].index)
merged_survey = merged_survey.drop(merged_survey[((merged_survey.ALT2 == 1)|(merged_survey.ALT2 == 2)) & ((merged_survey.ALT1Reversed== 5) | (merged_survey.ALT1Reversed== 4))].index)


print(merged_survey.shape)

(2196957, 48)
(2190612, 48)
(2184048, 48)

In [12]:
merged_survey.columns

Index(['email', 'name', 'pass_fail', 'right_question', 'wrong_question',
       'testID', 'testTakenTime', 'testDuration', 'testLevel', 'taskCompleted',
       'viewedVideoCases', 'viewedDemVideos', 'integrationCompleted',
       'practiceTestTaken', 'quality_Satisfaction1', 'ALT1NBR',
       'authenticProblems1', 'demonstration1', 'application1', 'activation1',
       'ALT2', 'ALT3', 'quality_Satisfaction2', 'demonstration2',
       'demonstration3', 'ALT4', 'authenticProblems2', 'integration1',
       'activation2', 'authenticProblems3', 'integration2',
       'demonstration4NBR', 'application3', 'quality_Satisfaction3NBR',
       'integration3', 'activation3', 'application4', 'demonstration5',
       'quality_Satisfaction4NBR', 'certificationDate',
       'certificationTestEarnedDate', 'IP', 'comments', 'email1',
       'ALT1Reversed', 'demonstration4Reversed',
       'quality_Satisfaction3Reversed', 'quality_Satisfaction4Reversed'],
      dtype='object')

In [13]:
#Drop the unnecessary columns which I think I don’t need in my analyses.
merged_survey=merged_survey.drop(['name', 'email1', 'certificationTestEarnedDate', 'certificationDate', 'IP'], axis=1)

In [14]:
# Drop the cloumns including items that needed to be reversed.

merged_survey=merged_survey.drop(['ALT1NBR', 'demonstration4NBR', 'quality_Satisfaction3NBR', 'quality_Satisfaction4NBR'], axis=1)
merged_survey.shape

(2184048, 39)

In [15]:
#show the number of null values for each feature
print(merged_survey[:].isnull().sum())

email                                  4
pass_fail                             52
right_question                        57
wrong_question                        59
testID                                60
testTakenTime                         59
testDuration                          60
testLevel                             94
taskCompleted                    2104278
viewedVideoCases                 2105015
viewedDemVideos                  2106174
integrationCompleted             2107423
practiceTestTaken                2107579
quality_Satisfaction1            2114628
authenticProblems1               2120259
demonstration1                   2119940
application1                     2120894
activation1                      2122137
ALT2                             2122436
ALT3                             2122346
quality_Satisfaction2            2121847
demonstration2                   2123259
demonstration3                   2122268
ALT4                             2121789
authenticProblems2               2123883
integration1                     2122390
activation2                      2123418
authenticProblems3               2124228
integration2                     2123277
application3                     2154184
integration3                     2154144
activation3                      2154195
application4                     2123926
demonstration5                   2123952
comments                          116274
ALT1Reversed                     2118281
demonstration4Reversed           2154410
quality_Satisfaction3Reversed    2153993
quality_Satisfaction4Reversed    2138921
dtype: int64

In [16]:
# filter out rows based on missing values in the columns: testLevel, email, testID
#the output above indicated that the feature testID has 2 missing values, which should not be a case. Since the assumption
# each datapoint should have a test ID. The code below shows the datapoints with missing values. Somehow these 
#two datapoints were not saved accurately. 

merged_survey=merged_survey[merged_survey.testLevel.notnull()]
merged_survey=merged_survey[merged_survey.email.notnull()]
merged_survey=merged_survey[merged_survey.testID.notnull()]

In [17]:
print(merged_survey[:].isnull().sum())

email                                  0
pass_fail                              0
right_question                         0
wrong_question                         0
testID                                 0
testTakenTime                          0
testDuration                           0
testLevel                              0
taskCompleted                    2104183
viewedVideoCases                 2104920
viewedDemVideos                  2106079
integrationCompleted             2107328
practiceTestTaken                2107484
quality_Satisfaction1            2114532
authenticProblems1               2120163
demonstration1                   2119844
application1                     2120798
activation1                      2122041
ALT2                             2122340
ALT3                             2122250
quality_Satisfaction2            2121751
demonstration2                   2123163
demonstration3                   2122172
ALT4                             2121693
authenticProblems2               2123787
integration1                     2122294
activation2                      2123322
authenticProblems3               2124132
integration2                     2123181
application3                     2154088
integration3                     2154048
activation3                      2154099
application4                     2123830
demonstration5                   2123856
comments                          116212
ALT1Reversed                     2118185
demonstration4Reversed           2154314
quality_Satisfaction3Reversed    2153897
quality_Satisfaction4Reversed    2138825
dtype: int64

In [18]:
print(merged_survey.pass_fail.unique())
print(len(merged_survey.pass_fail.unique()))

['FAIL' 'PASS' '3']
3

In [19]:
merged_survey.dtypes

email                             object
pass_fail                         object
right_question                    object
wrong_question                    object
testID                            object
testTakenTime                     object
testDuration                      object
testLevel                         object
taskCompleted                    float64
viewedVideoCases                 float64
viewedDemVideos                  float64
integrationCompleted             float64
practiceTestTaken                float64
quality_Satisfaction1            float64
authenticProblems1               float64
demonstration1                   float64
application1                     float64
activation1                      float64
ALT2                             float64
ALT3                             float64
quality_Satisfaction2            float64
demonstration2                   float64
demonstration3                   float64
ALT4                             float64
authenticProblems2               float64
integration1                     float64
activation2                      float64
authenticProblems3               float64
integration2                     float64
application3                     float64
integration3                     float64
activation3                      float64
application4                     float64
demonstration5                   float64
comments                          object
ALT1Reversed                     float64
demonstration4Reversed           float64
quality_Satisfaction3Reversed    float64
quality_Satisfaction4Reversed    float64
dtype: object

In [20]:
#Encoding objects to float and category

merged_survey[['right_question', 'wrong_question', 'testID', 'testTakenTime', 'testDuration']] = merged_survey[['right_question', 'wrong_question', 'testID', 'testTakenTime', 'testDuration']].astype('float')
merged_survey[['pass_fail','testLevel']] = merged_survey[['pass_fail','testLevel']].astype('category')

In [21]:
merged_survey.dtypes

email                              object
pass_fail                        category
right_question                    float64
wrong_question                    float64
testID                            float64
testTakenTime                     float64
testDuration                      float64
testLevel                        category
taskCompleted                     float64
viewedVideoCases                  float64
viewedDemVideos                   float64
integrationCompleted              float64
practiceTestTaken                 float64
quality_Satisfaction1             float64
authenticProblems1                float64
demonstration1                    float64
application1                      float64
activation1                       float64
ALT2                              float64
ALT3                              float64
quality_Satisfaction2             float64
demonstration2                    float64
demonstration3                    float64
ALT4                              float64
authenticProblems2                float64
integration1                      float64
activation2                       float64
authenticProblems3                float64
integration2                      float64
application3                      float64
integration3                      float64
activation3                       float64
application4                      float64
demonstration5                    float64
comments                           object
ALT1Reversed                      float64
demonstration4Reversed            float64
quality_Satisfaction3Reversed     float64
quality_Satisfaction4Reversed     float64
dtype: object

In [22]:
a=['quality_Satisfaction1', 'authenticProblems1',
       'demonstration1', 'application1', 'activation1', 'ALT2', 'ALT3',
       'quality_Satisfaction2', 'demonstration2', 'demonstration3', 'ALT4',
       'authenticProblems2', 'integration1', 'activation2',
       'authenticProblems3', 'integration2', 'application3', 'integration3',
       'activation3', 'application4', 'demonstration5',
       'ALT1Reversed', 'demonstration4Reversed',
       'quality_Satisfaction3Reversed', 'quality_Satisfaction4Reversed']
for b in a:
    merged_survey1=merged_survey[merged_survey[b].notnull()]
    #print(merged_survey[b])

In [23]:
merged_survey1.shape

(45127, 39)

In [24]:
print(merged_survey1[:].isnull().sum())

email                                0
pass_fail                            0
right_question                       0
wrong_question                       0
testID                               0
testTakenTime                        0
testDuration                         0
testLevel                            0
taskCompleted                      293
viewedVideoCases                   284
viewedDemVideos                    468
integrationCompleted               606
practiceTestTaken                  514
quality_Satisfaction1             1165
authenticProblems1                2966
demonstration1                    1878
application1                      2134
activation1                       2201
ALT2                              2139
ALT3                              1966
quality_Satisfaction2             1497
demonstration2                    2425
demonstration3                    1556
ALT4                              1337
authenticProblems2                2453
integration1                      1413
activation2                       1844
authenticProblems3                2295
integration2                      1622
application3                     31507
integration3                     31507
activation3                      31516
application4                      1807
demonstration5                    1848
comments                         41366
ALT1Reversed                      2292
demonstration4Reversed           31600
quality_Satisfaction3Reversed    31358
quality_Satisfaction4Reversed        0
dtype: int64

In [25]:
print(merged_survey[:].isnull().sum())

email                                  0
pass_fail                              0
right_question                         0
wrong_question                         0
testID                                 0
testTakenTime                          0
testDuration                           0
testLevel                              0
taskCompleted                    2104183
viewedVideoCases                 2104920
viewedDemVideos                  2106079
integrationCompleted             2107328
practiceTestTaken                2107484
quality_Satisfaction1            2114532
authenticProblems1               2120163
demonstration1                   2119844
application1                     2120798
activation1                      2122041
ALT2                             2122340
ALT3                             2122250
quality_Satisfaction2            2121751
demonstration2                   2123163
demonstration3                   2122172
ALT4                             2121693
authenticProblems2               2123787
integration1                     2122294
activation2                      2123322
authenticProblems3               2124132
integration2                     2123181
application3                     2154088
integration3                     2154048
activation3                      2154099
application4                     2123830
demonstration5                   2123856
comments                          116212
ALT1Reversed                     2118185
demonstration4Reversed           2154314
quality_Satisfaction3Reversed    2153897
quality_Satisfaction4Reversed    2138825
dtype: int64

In [26]:
#Which features are categorical and which features are not?

# The columns ['pass_fail','testLevel', 'highestEd', 'reason', 'level'] are categorical.
# I am going to convert these columns to categorical datatype.
# First, check the number of distinct values per categorical feature?

for col in merged_survey1:
    print(col, ':', len(merged_survey1[col].unique()))
    print(merged_survey1[col].unique())

email : 44097
['kmh6185@hotmail.com' 'maksudur076@gmail.com' 'cyxggq1995@sjtu.edu.cn'
 ... 's11055932@student.usp.ac.fj' 'robinspencer1959@yahoo.com'
 'jinyanxin1994@hotmail.com']
pass_fail : 2
[FAIL, PASS]
Categories (2, object): [FAIL, PASS]
right_question : 11
[ 7.  6.  8.  9.  3. 10.  4.  5.  2.  1.  0.]
wrong_question : 11
[ 3.  4.  2.  1.  7.  0.  6.  5.  8.  9. 10.]
testID : 45119
[3.24457497e+16 6.98910412e+21 1.19554614e+23 ... 1.61261113e+24
 1.14411253e+24 5.71361326e+23]
testTakenTime : 45127
[1.52008807e+09 1.52009113e+09 1.52009173e+09 ... 1.50227792e+09
 1.50228511e+09 1.50228690e+09]
testDuration : 398
[ 9.  13.5 36.4 32.7  2.  22.6  8.7  5.9 19.6  9.3 15.3  7.  33.8 16.3
 13.1 13.9  7.2  7.4 12.  10.3 23.6 24.5 10.9  8.8 10.5 15.2 29.6  8.3
 20.   5.7 10.4 15.8 14.7 26.  17.1  9.5  0.4  3.  36.3 31.6  7.3 29.3
 24.4 28.6  5.1 13.  10.7 11.5 23.4 38.8 33.7 12.2 16.8 22.3  5.3  3.9
 32.1 11.  15.1 11.2 10.8 17.   7.6  6.5  5.6 27.3 24.7 10.1 13.7 36.5
 15.  11.1 14.3 38.4  3.8 15.6 14.8 14.5  8.9  3.6 35.1 19.  27.1 13.4
  9.6 19.5 26.7 23.8 18.2 12.7 14.4 16.   8.2 19.4 24.2 13.2  5.2  9.4
 14.1 29.2 21.4  2.6 22.2  5.5  6.  20.1 14.9 13.8  4.6  9.2 15.9 10.
  7.9 16.9 25.1 23.1 27.4  6.9  6.8 11.4 34.5 16.4 10.6 12.1 17.2 17.9
 25.4  8.1  6.7 24.6 23.5  3.2 15.5  3.5 18.9 14.2 24.9 11.8  0.6 10.2
 28.  20.7 19.1 20.2 22.7  5.   6.3  5.8  4.8  4.4  9.1 12.8 38.3 16.1
 14.  17.3  9.7 12.5 26.1 12.6 15.4 31.7 17.7  2.7 19.7 18.1 16.2 29.
 21.2 23.2  8.  21.8  4.  18.5 17.5 39.3  2.8  4.9 20.3 19.9 37.5 17.6
  5.4 36.2  7.1  8.5 21.1 35.5 26.6 36.1  6.2 11.3 38.2  7.5 22.1 25.6
 12.3 20.8 16.5 25.2 19.8 29.7 12.4 24.8 24.3  7.7 27.2  4.2  6.1  4.7
 13.6 17.4  3.3 21.5 13.3  9.8  2.9  4.3  8.4 21.7  7.8  8.6 37.2  6.6
 11.6 26.3 30.5 14.6  3.1  6.4 21.9 19.2  3.7 29.8 32.9 23.  11.7 28.9
 27.9 11.9 37.  28.4 15.7 33.3 16.6 31.8  2.2  0.8 31.9 20.5 22.5 20.9
 18.8  4.5 30.1 12.9 18.   2.3 16.7  1.9 27.7 21.6 18.6 18.3 25.  20.4
 18.7 26.5 38.7 29.5 21.   1.1 25.3 20.6 19.3 37.4 23.3 22.9  2.1 32.3
  4.1  1.2 22.4  1.8 26.4 35.8 18.4  9.9 26.8 26.2  3.4 36.8 22.  39.1
 28.8 22.8 34.3 38.5 34.7 38.9 30.9 36.  38.  39.7 37.1 29.4 28.1 28.3
  0.5  0.3  1.4 27.5 17.8 36.9 32.  25.5 39.2 30.4 27.6 29.9 35.9 32.5
 34.8  2.5 28.2 21.3  0.9 23.9  1.7 31.5 30.8  1.6 25.7 31.   1.5 27.8
 30.  37.8 31.1 27.   2.4 39.4 24.1  0.7 31.2 36.6 39.5 30.3 40.  25.9
 30.2 30.7 32.6 31.4 33.  34.6 30.6 35.6 35.3 34.4 38.6 35.4 36.7 35.2
 39.6 39.8 23.7 37.9 37.3 29.1 37.6 25.8 32.8 28.7 39.  24.  31.3 33.2
 34.1  1.  32.4 26.9 34.  34.2 33.4 35.7 33.5 34.9 33.9  1.3 35.  28.5
 32.2 33.1 39.9 33.6 37.7 38.1]
testLevel : 2
[UG, GR]
Categories (2, object): [UG, GR]
taskCompleted : 7
[ 5.  1.  0.  2.  4.  3. nan]
viewedVideoCases : 5
[ 3.  1.  2.  0. nan]
viewedDemVideos : 5
[ 3.  2.  0.  1. nan]
integrationCompleted : 5
[ 3.  0.  1.  2. nan]
practiceTestTaken : 5
[ 3.  1.  2.  0. nan]
quality_Satisfaction1 : 6
[ 4.  5.  3.  2. nan  1.]
authenticProblems1 : 6
[ 5. nan  3.  4.  2.  1.]
demonstration1 : 6
[ 5.  4.  3.  2.  1. nan]
application1 : 6
[ 5.  4. nan  3.  1.  2.]
activation1 : 6
[ 5.  4.  3. nan  1.  2.]
ALT2 : 6
[ 4.  3.  1.  5. nan  2.]
ALT3 : 6
[ 5.  4.  2.  3. nan  1.]
quality_Satisfaction2 : 6
[ 4.  5.  3.  2.  1. nan]
demonstration2 : 6
[ 5.  4.  1.  3. nan  2.]
demonstration3 : 6
[ 5.  4.  3.  2. nan  1.]
ALT4 : 6
[ 5.  4.  2. nan  3.  1.]
authenticProblems2 : 6
[ 5.  4.  2.  3. nan  1.]
integration1 : 6
[ 5.  4.  3.  2. nan  1.]
activation2 : 6
[ 5.  4.  2.  3. nan  1.]
authenticProblems3 : 6
[ 5.  4.  3.  2. nan  1.]
integration2 : 6
[ 5.  4.  3.  2. nan  1.]
application3 : 6
[ 5.  4.  2. nan  3.  1.]
integration3 : 6
[ 5.  4.  2.  3.  1. nan]
activation3 : 6
[ 5.  4.  3.  2. nan  1.]
application4 : 6
[ 5.  4.  3.  2. nan  1.]
demonstration5 : 6
[ 5. nan  2.  4.  3.  1.]
comments : 3612
[nan
 'great training tool, i wish i had this available years ago when i started school, citations have always been hard for me. One thing i wish we had was a tutorial such as this on the reference page information.'
 'all the tutorials helped me to understand plagiarism' ...
 "The only things I found less helpful were the videos where people acted out little skits. Those were very basic and not really necessary. The other problem I had is if you know it is plagiarism, it seems a bit of overkill to try to figure out if it's paraphrasing plagiarism or word-for-word according to all the little rules."
 'The portions of the videos I viewed were ridiculous. I would much prefer a typed sheet of information in a condensed and easily understood format with a few examples. That would have taken much less time than all of the practice questions.'
 'I definitely received information that provided some clarity, that I will be implement on future work.']
ALT1Reversed : 6
[ 4.  5.  3.  2. nan  1.]
demonstration4Reversed : 6
[ 5. nan  4.  3.  2.  1.]
quality_Satisfaction3Reversed : 6
[ 4.  5. nan  2.  3.  1.]
quality_Satisfaction4Reversed : 5
[4. 5. 2. 3. 1.]

In [27]:
#WORKING ON THE DATASET INCLUDING DEMOGRAPHIC DATA

In [28]:
#reading and loading the registration dataset into a dataframe.
reg=pd.read_csv('/Users/cesurdagli/Desktop/Capstone Project/users.csv') 
reg.shape

/Users/cesurdagli/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(571963, 12)

In [29]:
reg.columns

Index(['email', 'firstname', 'lastname', 'age', 'highestEd', 'degreeOther',
       'reason', 'reasonOther', 'level', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11'],
      dtype='object')

In [31]:
reg=reg.drop(['Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11'], axis=1)

In [32]:
#the number of missing values per feature
print(reg[:].isnull().sum())

email            0
firstname        0
lastname         4
age              0
highestEd        3
degreeOther     83
reason           9
reasonOther    256
level           43
dtype: int64

In [33]:
reg1=reg[reg.lastname.notnull()]

In [34]:
#the number of missing values per feature
print(reg1[:].isnull().sum())

email            0
firstname        0
lastname         0
age              0
highestEd        3
degreeOther     79
reason           9
reasonOther    252
level           43
dtype: int64

In [35]:
a=['highestEd', 'reason', 'level']
for col in a:
    print(col, ':', len(reg1[col].unique()))
    print(reg1[col].unique())

highestEd : 14
[' ' ' DD' ' MD' ' HS' ' BD' ' AD' ' OT' nan 'OT' 'HS' 'MD' 'AD' 'DD' 'BD']
reason : 7
[' ' ' review' ' assignment' ' learn' ' curious' ' other' nan]
level : 5
[' ' ' confident' ' some' ' little' nan]

In [36]:
#merging two dataframes on emails in the survey dataframe

merged=pd.merge(left=merged_survey1, right=reg1, left_on='email', right_on='email', how='left')
print(merged.shape)
print(merged.columns)

(45127, 47)
Index(['email', 'pass_fail', 'right_question', 'wrong_question', 'testID',
       'testTakenTime', 'testDuration', 'testLevel', 'taskCompleted',
       'viewedVideoCases', 'viewedDemVideos', 'integrationCompleted',
       'practiceTestTaken', 'quality_Satisfaction1', 'authenticProblems1',
       'demonstration1', 'application1', 'activation1', 'ALT2', 'ALT3',
       'quality_Satisfaction2', 'demonstration2', 'demonstration3', 'ALT4',
       'authenticProblems2', 'integration1', 'activation2',
       'authenticProblems3', 'integration2', 'application3', 'integration3',
       'activation3', 'application4', 'demonstration5', 'comments',
       'ALT1Reversed', 'demonstration4Reversed',
       'quality_Satisfaction3Reversed', 'quality_Satisfaction4Reversed',
       'firstname', 'lastname', 'age', 'highestEd', 'degreeOther', 'reason',
       'reasonOther', 'level'],
      dtype='object')

In [38]:
a=['pass_fail', 'testLevel', 'highestEd', 'reason', 'level']
for col in a:
    print(col, ':', len(merged[col].unique()))
    print(merged[col].unique())

pass_fail : 2
[FAIL, PASS]
Categories (2, object): [FAIL, PASS]
testLevel : 2
[UG, GR]
Categories (2, object): [UG, GR]
highestEd : 11
[' HS' ' BD' ' AD' ' MD' ' ' ' OT' ' DD' nan 'BD' 'HS' 'AD']
reason : 7
[' assignment' ' learn' ' other' ' ' nan ' curious' ' review']
level : 5
[' confident' ' some' ' ' ' little' nan]

In [39]:
# Recoding the categorical values
clean_nums = {'highestEd': {' DD':'DD', ' MD':'MD', ' BD':'BD', ' HS':'HS', ' AD':'AD', ' OT':'OT'},
                  'reason': {' review':'review', ' learn':'learn', ' assignment':'assignment', ' curious':'curious', ' other':'other'},
                  'level': {' confident':'confident', ' some':'some', ' little':'little'}}
merged.replace(clean_nums, inplace=True)
merged[['highestEd', 'reason', 'level']].head()

  highestEd      reason      level
0        HS  assignment  confident
1        BD  assignment  confident
2        BD  assignment  confident
3        BD  assignment  confident
4        AD  assignment       some

In [40]:
#What is the type of each feature?
merged.dtypes

email                              object
pass_fail                        category
right_question                    float64
wrong_question                    float64
testID                            float64
testTakenTime                     float64
testDuration                      float64
testLevel                        category
taskCompleted                     float64
viewedVideoCases                  float64
viewedDemVideos                   float64
integrationCompleted              float64
practiceTestTaken                 float64
quality_Satisfaction1             float64
authenticProblems1                float64
demonstration1                    float64
application1                      float64
activation1                       float64
ALT2                              float64
ALT3                              float64
quality_Satisfaction2             float64
demonstration2                    float64
demonstration3                    float64
ALT4                              float64
authenticProblems2                float64
integration1                      float64
activation2                       float64
authenticProblems3                float64
integration2                      float64
application3                      float64
integration3                      float64
activation3                       float64
application4                      float64
demonstration5                    float64
comments                           object
ALT1Reversed                      float64
demonstration4Reversed            float64
quality_Satisfaction3Reversed     float64
quality_Satisfaction4Reversed     float64
age                               float64
highestEd                          object
degreeOther                        object
reason                             object
reasonOther                        object
level                              object
dtype: object

In [41]:
merged[[
       'highestEd', 'reason','level']] = merged[[
       'highestEd', 'reason','level' ]].astype('category')
print(merged.dtypes)

email                              object
pass_fail                        category
right_question                    float64
wrong_question                    float64
testID                            float64
testTakenTime                     float64
testDuration                      float64
testLevel                        category
taskCompleted                     float64
viewedVideoCases                  float64
viewedDemVideos                   float64
integrationCompleted              float64
practiceTestTaken                 float64
quality_Satisfaction1             float64
authenticProblems1                float64
demonstration1                    float64
application1                      float64
activation1                       float64
ALT2                              float64
ALT3                              float64
quality_Satisfaction2             float64
demonstration2                    float64
demonstration3                    float64
ALT4                              float64
authenticProblems2                float64
integration1                      float64
activation2                       float64
authenticProblems3                float64
integration2                      float64
application3                      float64
integration3                      float64
activation3                       float64
application4                      float64
demonstration5                    float64
comments                           object
ALT1Reversed                      float64
demonstration4Reversed            float64
quality_Satisfaction3Reversed     float64
quality_Satisfaction4Reversed     float64
age                               float64
highestEd                        category
degreeOther                        object
reason                           category
reasonOther                        object
level                            category
dtype: object

In [42]:
#the number of missing values per feature
print((merged[:].isnull().sum())/len(merged))

email                            0.000000
pass_fail                        0.000000
right_question                   0.000000
wrong_question                   0.000000
testID                           0.000000
testTakenTime                    0.000000
testDuration                     0.000000
testLevel                        0.000000
taskCompleted                    0.006493
viewedVideoCases                 0.006293
viewedDemVideos                  0.010371
integrationCompleted             0.013429
practiceTestTaken                0.011390
quality_Satisfaction1            0.025816
authenticProblems1               0.065726
demonstration1                   0.041616
application1                     0.047289
activation1                      0.048773
ALT2                             0.047400
ALT3                             0.043566
quality_Satisfaction2            0.033173
demonstration2                   0.053737
demonstration3                   0.034480
ALT4                             0.029627
authenticProblems2               0.054358
integration1                     0.031312
activation2                      0.040862
authenticProblems3               0.050856
integration2                     0.035943
application3                     0.698185
integration3                     0.698185
activation3                      0.698385
application4                     0.040043
demonstration5                   0.040951
comments                         0.916657
ALT1Reversed                     0.050790
demonstration4Reversed           0.700246
quality_Satisfaction3Reversed    0.694883
quality_Satisfaction4Reversed    0.000000
age                              0.023822
highestEd                        0.023822
degreeOther                      0.023932
reason                           0.023844
reasonOther                      0.024287
level                            0.023888
dtype: float64

In [43]:
#replacing empty values with null values
merged=merged.replace(r'^\s+$', np.nan, regex=True)

In [44]:
#the number of missing values per feature
print(merged[:].isnull().sum())

email                                0
pass_fail                            0
right_question                       0
wrong_question                       0
testID                               0
testTakenTime                        0
testDuration                         0
testLevel                            0
taskCompleted                      293
viewedVideoCases                   284
viewedDemVideos                    468
integrationCompleted               606
practiceTestTaken                  514
quality_Satisfaction1             1165
authenticProblems1                2966
demonstration1                    1878
application1                      2134
activation1                       2201
ALT2                              2139
ALT3                              1966
quality_Satisfaction2             1497
demonstration2                    2425
demonstration3                    1556
ALT4                              1337
authenticProblems2                2453
integration1                      1413
activation2                       1844
authenticProblems3                2295
integration2                      1622
application3                     31507
integration3                     31507
activation3                      31516
application4                      1807
demonstration5                    1848
comments                         41366
ALT1Reversed                      2292
demonstration4Reversed           31600
quality_Satisfaction3Reversed    31358
quality_Satisfaction4Reversed        0
age                               1075
highestEd                         1075
degreeOther                      42782
reason                            1076
reasonOther                      44868
level                             1078
dtype: int64

In [45]:
# Drop all those who did not complete the survey
merged1 = merged.dropna(axis=0, subset=['quality_Satisfaction1', 'authenticProblems1',
       'demonstration1', 'application1', 'activation1', 'ALT2', 'ALT3',
       'quality_Satisfaction2', 'demonstration2', 'demonstration3', 'ALT4',
       'authenticProblems2', 'integration1', 'activation2',
       'authenticProblems3', 'integration2', 'application3', 'integration3',
       'activation3', 'application4', 'demonstration5',
       'ALT1Reversed', 'demonstration4Reversed',
       'quality_Satisfaction3Reversed', 'quality_Satisfaction4Reversed'])
#print(merged1.head())
print(merged1.shape)
print(merged1[:].isnull().sum())

(10257, 45)
email                                0
pass_fail                            0
right_question                       0
wrong_question                       0
testID                               0
testTakenTime                        0
testDuration                         0
testLevel                            0
taskCompleted                       39
viewedVideoCases                    31
viewedDemVideos                     71
integrationCompleted                91
practiceTestTaken                   64
quality_Satisfaction1                0
authenticProblems1                   0
demonstration1                       0
application1                         0
activation1                          0
ALT2                                 0
ALT3                                 0
quality_Satisfaction2                0
demonstration2                       0
demonstration3                       0
ALT4                                 0
authenticProblems2                   0
integration1                         0
activation2                          0
authenticProblems3                   0
integration2                         0
application3                         0
integration3                         0
activation3                          0
application4                         0
demonstration5                       0
comments                          9418
ALT1Reversed                         0
demonstration4Reversed               0
quality_Satisfaction3Reversed        0
quality_Satisfaction4Reversed        0
age                                239
highestEd                          239
degreeOther                       9667
reason                             239
reasonOther                      10200
level                              239
dtype: int64

In [46]:
#Calculating average of each of seven categories: Quality Satisfaction, Authentic Problems, ALT, Activation, Demonstration,
#Application, and Integration

merged['ave_quality_Satisfaction']=merged[['quality_Satisfaction1', 'quality_Satisfaction2', "quality_Satisfaction3Reversed", 'quality_Satisfaction4Reversed']].mean(axis=1)
merged['ave_authenticProblems']=merged[['authenticProblems1', 'authenticProblems2', 'authenticProblems3']].mean(axis=1)
merged['ave_ALT']=merged[['ALT2', 'ALT3', 'ALT4', 'ALT1Reversed']].mean(axis=1)
merged['ave_activation']=merged[['activation1', 'activation2', 'activation3']].mean(axis=1)
merged['ave_demonstration']=merged[['demonstration1', 'demonstration2', 'demonstration2','demonstration4Reversed','demonstration5']].mean(axis=1)
merged['ave_application']=merged[['application1', 'application3','application4']].mean(axis=1)
merged['ave_application']=merged[['application1', 'application3','application4']].mean(axis=1)
merged['ave_integration']=merged[['integration1', 'integration2','integration3']].mean(axis=1)
merged.columns

Index(['email', 'pass_fail', 'right_question', 'wrong_question', 'testID',
       'testTakenTime', 'testDuration', 'testLevel', 'taskCompleted',
       'viewedVideoCases', 'viewedDemVideos', 'integrationCompleted',
       'practiceTestTaken', 'quality_Satisfaction1', 'authenticProblems1',
       'demonstration1', 'application1', 'activation1', 'ALT2', 'ALT3',
       'quality_Satisfaction2', 'demonstration2', 'demonstration3', 'ALT4',
       'authenticProblems2', 'integration1', 'activation2',
       'authenticProblems3', 'integration2', 'application3', 'integration3',
       'activation3', 'application4', 'demonstration5', 'comments',
       'ALT1Reversed', 'demonstration4Reversed',
       'quality_Satisfaction3Reversed', 'quality_Satisfaction4Reversed', 'age',
       'highestEd', 'degreeOther', 'reason', 'reasonOther', 'level',
       'ave_quality_Satisfaction', 'ave_authenticProblems', 'ave_ALT',
       'ave_activation', 'ave_demonstration', 'ave_application',
       'ave_integration'],
      dtype='object')

In [ ]:
merged1.to_csv('Feb17NoNull_Merged.csv')

In [ ]:
merged.to_csv('Feb17SomeNull_Merged.csv')